// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureAndProcess(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CaptureAndProcess'](arg1, arg2, arg3, arg4);
}

export function ExitApp() {
  return window['go']['main']['App']['ExitApp']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function SaveCalibration(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveCalibration'](arg1, arg2, arg3, arg4);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function TriggerCapture() {
  return window['go']['main']['App']['TriggerCapture']();
}
