// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CaptureAndProcess(arg1:number,arg2:number,arg3:number,arg4:number):Promise<string>;

export function ExitApp():Promise<void>;

export function FetchAvailableModels():Promise<Array<string>>;

export function GetConfig():Promise<main.Config>;

export function GetHistory():Promise<Array<main.HistoryEntry>>;

export function LoadConfig():Promise<main.Config>;

export function LogFromJS(arg1:string):Promise<void>;

export function RemoveRecentModel(arg1:string):Promise<main.Config>;

export function SaveCalibration(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function SaveConfig(arg1:main.Config):Promise<boolean>;

export function TriggerCapture():Promise<void>;
